### ISSUE TITLE
How do I set BLCK up?

### ISSUE THREAD

**Issue by Unzor** [FlowVix/BLCK#2]

**Comment by FlowVix** [comment]
BLCK is still in a very early stage and not usable yet to generate SPWN code

**Comment by LukaTV939** [comment]
You build BLCK on godot engine

**Comment by Megarion** [comment]
[you trying to learn spwn](https://media.discordapp.net/attachments/791323294796087308/881480945373413426/caption.gif)

**Comment by DemonLordDiablo** [comment]
what is wrong, i tried loading the zip file and the godot file into the web version of godot, but it didn't load, am i doing something wrong or what? please help.

**Comment by SpeckyYT** [comment]
Since when do you load a zip file into godot

**Comment by DemonLordDiablo** [comment]
> Since when do you load a zip file into godot

![image](https://user-images.githubusercontent.com/87140755/132209858-66d20ad9-c397-46c3-97ab-762d1f75fa87.png)

**Comment by sertdfyguhi** [comment]
spcky

**Comment by SpeckyYT** [comment]
> spcky

cringr 💀

**Comment by sertdfyguhi** [comment]
@SpckyYT

**Comment by Megarion** [comment]
> spcky

cringr 💀

**Comment by DemonLordDiablo** [comment]
> > spcky
> 
> cringr 💀



> @SpckyYT



> > spcky
> 
> cringr 💀



> spcky

what do you all mean?

**Comment by sertdfyguhi** [comment]
spck

**Comment by Megarion** [comment]
blck*

**Comment by DemonLordDiablo** [comment]
can someone actually help me figure out how to do this???!

**Comment by SpeckyYT** [comment]
> can someone actually help me figure out how to do this???!

idk (blck isn't stable yet)

**Comment by sertdfyguhi** [comment]
CLOSE THIS ISSUE :3

**Comment by zTags** [comment]
how me set bloock up

**Comment by Megarion** [comment]
close this issue flow

**Comment by sertdfyguhi** [comment]
> how me set bloock up

you don't

**Comment by Unzor** [comment]
aaaaaaaaaaaaa

**Comment by Darkar25** [comment]
why closed

**Comment by sertdfyguhi** [comment]
cause you cant

**Comment by Darkar25** [comment]
> cause you cant

:с

**Comment by Megarion** [comment]
rip lol
